version: '3.8'
services:
  test_master:
    container_name: 'TestMaster'
    build:
      context: .
    volumes:
      - ..:/home/volume
      - test-master-bashhistory:/commandhistory
    working_dir: /home/volume
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - sleep infinity

volumes:
  test-master-bashhistory:
