Resources:

  DatabaseAppCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /${self:custom.servicePrefix}/AppCredentials
      Description: RDS app credentials
      GenerateSecretString:
        SecretStringTemplate: !Sub |
          {
            "username": "${self:custom.rds.appUsername}"
          }
        GenerateStringKey: password
        ExcludeCharacters: '"''(),./:;<=>?@[\]^`{|}~'
  DatabaseAppCredentialsAttachment:
    DependsOn:
      - Database
      - DatabaseAppCredentials
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DatabaseAppCredentials
      TargetId: ${self:custom.rds.arn}
      TargetType: AWS::RDS::DBInstance
      